# Generated by Django 4.2.9 on 2024-02-06 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_type', models.CharField(choices=[('contributor', 'Contributor'), ('borrower', 'Borrower')], max_length=20)),
                ('review_result', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=20)),
                ('review_comment', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_place', models.CharField(choices=[('taipei', 'Taipei'), ('yilan', 'Yilan')], max_length=20)),
                ('airdrop_wallet_address', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
