# Generated by Django 4.2.10 on 2024-04-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_review_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('as_contributor', 'As Contributor'), ('as_borrower', 'As Borrower')], max_length=20),
        ),
    ]
