# Generated by Django 4.2.11 on 2024-05-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_profile_average_overdue_pick_up_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="average_decision_making_minute",
            field=models.IntegerField(default=0),
        ),
    ]
