# Generated by Django 4.2.10 on 2024-02-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0004_alter_item_contributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_available_day',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_available_time',
        ),
    ]
