# Generated by Django 4.2.10 on 2024-03-03 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0005_remove_item_item_available_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('sporting-goods', 'Sporting-Goods'), ('books, movies & music', 'Books, Movies & Music'), ('home & garden', 'Home & Garden'), ('toys & hobbies', 'Toys & Hobbies'), ('everything else', 'Everything Else')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
