# Generated by Django 4.2.11 on 2024-04-21 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0006_item_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_deposit_require',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
