# Generated by Django 4.2.11 on 2024-05-28 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contribute", "0008_alter_item_item_deposit_require"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="contributor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
