# Generated by Django 4.2.10 on 2024-02-18 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contribute', '0004_alter_item_contributor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('returndate', models.DateTimeField()),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('insufficient_balance', 'Insufficient Balance'), ('cancel_order', 'Cancel Order'), ('paid', 'Paid'), ('deny', 'Deny'), ('return', 'Return')], max_length=20)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contribute.item')),
            ],
        ),
    ]
