# Generated by Django 4.2.10 on 2024-03-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_rename_returndate_order_end_time_order_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('insufficient_balance', 'Insufficient Balance'), ('cancel_order', 'Cancel Order'), ('paid', 'Paid'), ('accept', 'Accept'), ('deny', 'Deny'), ('return', 'Return')], max_length=20),
        ),
    ]
