# Generated by Django 4.2.10 on 2024-03-13 16:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0006_item_item_category'),
        ('borrow', '0004_alter_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='request_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contribute.item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('wait_to_pay', 'Wait To Pay'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('accept', 'Accept'), ('deny', 'Deny'), ('cancel_order', 'Cancel Order'), ('get_item', 'Get Item'), ('return', 'Return'), ('finish', 'Finish')], max_length=20),
        ),
    ]
