# Generated by Django 4.2.11 on 2024-04-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0006_order_breakage_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('wait_to_pay', 'Wait To Pay'), ('pending', 'Pending'), ('unpaid', 'Unpaid'), ('accept', 'Accept'), ('deny', 'Deny'), ('cancel_order', 'Cancel Order'), ('get_item', 'Get Item'), ('return_item', 'Return Item'), ('borrower_comment', 'Borrower Comment'), ('finish', 'Finish')], max_length=20),
        ),
    ]
