# Generated by Django 4.2.11 on 2024-05-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrow", "0008_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="airdropAmount",
            field=models.IntegerField(default=0),
        ),
    ]
